FAQ/urls.py
from django.urls import path
from . import views

app_name = 'FAQ'

urlpatterns = [
    path('', views.faqViews, name='faq'),
]

accmanager/urls.py
from django.urls import path

from . import views

app_name = 'accmgr'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('<int:id>', views.profile, name='profile-id'),
    path('edit', views.edit, name='edit'),
    path('edit/<int:id>', views.edit, name='edit-id'),
    path('riwayat', views.riwayat, name='riwayat'),
    path('riwayat/<int:id>', views.riwayat, name='riwayat-id'),
    path('status', views.status, name='status'),
    path('status/<int:id>', views.status, name='status-id'),
]

buangsampah/urls.py
from django.urls import path
from . import views

app_name = 'buangsampah'

urlpatterns = [
    path('', views.snippet_detail, name ='buangsampah'),
]

helloworld/urls.py
from django.urls import path

from . import views

app_name = 'helloworld'

urlpatterns = [
    path('helloworld/', views.hello, name='hello'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homeViews, name='home'),
]

trashbank/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('FAQ/', views.faq, name='faq'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('profile/', include('accmanager.urls')),
    # path('', include('helloworld.urls')),
    path('buangsampah/', include('buangsampah.urls')),
]

tutorial/urls.py
from django.urls import path
from . import views

app_name = 'tutorial'

urlpatterns = [
    path('', views.tutorialViews, name='tutorial'),
]

FAQ/models.py
from django.db import models

# Create your models here.

accmanager/models.py
from django.db import models

# Create your models here.

class Dummy(object):
    pass

class Account(models.Model):
    name = models.CharField(max_length=10485760, default='')
    job = models.CharField(max_length=10485760, default='')
    address = models.CharField(max_length=10485760, default='')
    balance = models.IntegerField(default=0)

class Riwayat(models.Model):
    owner_id = models.ForeignKey('Account', on_delete=models.CASCADE, null=True)
    jenis = models.CharField(max_length=10485760, default='')
    berat = models.IntegerField()
    lokasi = models.CharField(max_length=10485760, default='')
    diterima = models.BooleanField(default=False)
    pass

buangsampah/models.py
from django.db import models
from multiselectfield import MultiSelectField

class Snippet(models.Model):
    TRASH_CHOICES = (
        ('Plastik', 'Plastik'),
        ('Kertas', 'Kertas'), 
        ('Sisa Makanan', 'Sisa Makanan'),
        ('Logam', 'Logam'),
        ('Kaca', 'Kaca'),
        ('Lain-lain', 'Lain-lain')
    )
    
    berat_Sampah = models.CharField(max_length = 100)
    lokasi_Rumah = models.TextField()
    kategori_Sampah = MultiSelectField(choices = TRASH_CHOICES)
    status_Diterima = models.BooleanField(default=False)

    def __str__(self):
        return self.lokasi_Rumah
        return self.kategori_Sampah
        return self.berat_Sampah

helloworld/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

lists/models.py
from django.db import models

# Create your models here.

tutorial/models.py
from django.db import models

# Create your models here.

accmanager/forms.py
from django import forms
from .models import Account

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

buangsampah/forms.py
from django import forms
from .models import Snippet



class ContactForm(forms.Form):
    name = forms.CharField(label = 'Berat Sampah')
    email = forms.EmailField(label = 'E-Mail')
    category = forms.ChoiceField(label = 'Kategori Sampah', choices=[('plastik', 'Plastik'), ('kertas', 'Kertas'),('sisa makanan', 'Sisa Makanan'),('logam', 'Logam'),('kaca','Kaca'),('lain-lain','Lain-lain')])
    subject = forms.CharField(required = False)
    body = forms.CharField(widget = forms.Textarea)
   

    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    

    


class SnippetForm(forms.ModelForm):

    class Meta:
        model = Snippet
        exclude = ['status_Diterima']

FAQ/views.py
from django.shortcuts import render, redirect

# Create your views here.
def faqViews(request):
    return render(request, 'FAQ.html')

accmanager/views.py
from django.shortcuts import render
from .models import Dummy, Account, Riwayat
from buangsampah.models import Snippet
from django.http import HttpResponseRedirect
from django.urls import reverse

def snippet_to_account(snippet_query):
    _return = []
    for i in snippet_query:
        dummy = Dummy()
        dummy.berat = i.berat_Sampah
        dummy.lokasi = i.lokasi_Rumah
        dummy.jenis = '|'.join(i.kategori_Sampah)
        _return.append(dummy)
    return _return


# Create your views here.

def profile(request, id=None):
    link_riwayat = reverse('accmgr:riwayat')
    link_status = reverse('accmgr:status')
    link_edit = reverse('accmgr:edit')

    filtered = Account.objects.filter(id=id)
    if len(filtered) > 0:
        selaccount = filtered.first()

        selbalance = str(selaccount.balance)
        balance = '.'.join([selbalance[::-1][i:i+3] for i in range(0, len(selbalance), 3)])[::-1]
        balance = 'Rp ' + balance + ',00'
        link_riwayat = reverse('accmgr:riwayat-id', args=[selaccount.id])
        link_status = reverse('accmgr:status-id', args=[selaccount.id])
        link_edit = reverse('accmgr:edit-id', args=[selaccount.id])
    elif len(Account.objects.all()) > 0:
        selaccount = Account.objects.first()
        return HttpResponseRedirect(reverse('accmgr:profile-id', args=[selaccount.id]))
    elif id != None:
        return HttpResponseRedirect(reverse('accmgr:profile'))
    else:
        selaccount = Dummy()
        selaccount.name = 'Dummy Account'
        selaccount.job = 'Students'
        selaccount.address = 'depok'
        selaccount.id = None
        balance = 'Rp 18.000,00'

    return render(request, 'profile.html', context={
        'selaccount' : selaccount,
        'balance' : balance,
        'link_riwayat' : link_riwayat,
        'link_status' : link_status,
        'link_edit' : link_edit,
    })

def edit(request, id=None):
    return HttpResponseRedirect(reverse('accmgr:profile'))

def riwayat(request, id=None):
    # list_riwayat = Riwayat.objects.filter(owner_id=id, diterima=True)
    list_riwayat = snippet_to_account(Snippet.objects.filter(status_Diterima=True))
    return render(request, 'riwayat.html', context={
        'list_riwayat' : list_riwayat,
        'owner' : id if id != None else 1,
    })

def status(request, id=None):
    # list_riwayat = Riwayat.objects.filter(owner_id=id, diterima=False)
    list_riwayat = snippet_to_account(Snippet.objects.filter(status_Diterima=False))
    return render(request, 'status.html', context={
        'list_riwayat' : list_riwayat,
        'owner' : id if id != None else 1,
    })

buangsampah/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ContactForm, SnippetForm

def contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():

            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            category = form.cleaned_data['category']

            print(name,email,category)

    form = ContactForm()
    return render(request, 'form.html', {'form': form})


def snippet_detail(request):
    if request.method == 'POST':
        form = SnippetForm(request.POST)
        if form.is_valid():
            print("VALID")
            form.save()
    
    form = SnippetForm()
    return render(request, 'form.html', {'form': form})

helloworld/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request, 'hello.html')

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def homeViews(request):
    return render(request, 'home.html')

lists/views.py
from django.shortcuts import render

# Create your views here.

trashbank/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'new_home.html')

def faq(request):
    return render(request, 'new_faq.html')

def tutorial(request):
    return render(request, 'new_tutorial.html')

tutorial/views.py
from django.shortcuts import render, redirect

# Create your views here.
def tutorialViews(request):
    return render(request, 'tutorial.html')

accmanager/templates/edit.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">

    <title>TRASH-IT</title>
</head>

<body>
    <!-- Navigation Bar -->
    {% include 'navbar.html' with profile_stats='active' %}

    
    <!-- Page Content Start -->
    <form action="post">
        <div class="banner">
            <div class="text-center">
                <h2>
                    <input type="text" name="name" maxlength="2147483647" required id="id_name" value={{ selaccount.name }}>
                </h2>
                <!-- <h2>{{ selaccount.name }}</h2> -->
            </div>
        </div>
    
        <h3>
            <div class="row profile-info">
                <div class="col-1 col-lg-2"></div>
                <div class="col-10 col-lg-8 row">
                    <div class="col-5 col-lg-4 label">
                        Pekerjaan
                    </div>
                    <div class="col-7 col-lg-8 data">
                        {{ selaccount.job }}
                    </div>
                    <div class="col-5 col-lg-4 label">
                        Tempat Tinggal
                    </div>
                    <div class="col-7 col-lg-8 data">
                        {{ selaccount.address }}
                    </div>
                    <div class="col-5 col-lg-4 label">
                        Dompetku
                    </div>
                    <div class="col-7 col-lg-8 data">
                        <h1>{{ balance }}</h1>
                    </div>
    
                    <div class="col-12" id="card-container">
                        <a href={{ link_riwayat }}><card id="left">Riwayat</card></a>
                        <a href={{ link_status }}><card id="right">Status Sampah</card></a>
                    </div>
                </div>
                <div class="col-1 col-lg-2">
                    <img src="https://image.flaticon.com/icons/svg/1159/1159633.svg" style="height: 30px;">
                </div>
            </div>
        </h3>
    </form>
    <!-- Page Content End -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

accmanager/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with profile_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">
{% endblock %}
    
{% block content %}
<div class="banner">
    <div class="text-center">
        <h2>{{ selaccount.name }}</h2>
    </div>
</div>

<h3>
    <div class="row profile-info">
        <div class="col-1 col-lg-2"></div>
        <div class="col-10 col-lg-8 row">
            <div class="col-5 col-lg-4 label">
                Pekerjaan
            </div>
            <div class="col-7 col-lg-8 data">
                {{ selaccount.job }}
            </div>
            <div class="col-5 col-lg-4 label">
                Tempat Tinggal
            </div>
            <div class="col-7 col-lg-8 data">
                {{ selaccount.address }}
            </div>
            <div class="col-5 col-lg-4 label">
                Dompetku
            </div>
            <div class="col-7 col-lg-8 data">
                <h1>{{ balance }}</h1>
            </div>

            <div class="col-12" id="card-container">
                <a href="{{ link_riwayat }}"><card id="left">Riwayat</card></a>
                <a href="{{ link_status }}"><card id="right">Status Sampah</card></a>
            </div>
        </div>
        <div class="col-1 col-lg-2">
            <!-- <a href={{ link_edit }}><img src="https://image.flaticon.com/icons/svg/1159/1159633.svg" style="height: 30px;"></a> -->
        </div>
    </div>
</h3>
{% endblock %}

home/templates/home.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style_home.css' %}">

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">

    <title>TRASH-IT</title>
</head>

<body>
    <!-- Navigation Bar -->
    {% include 'navbar.html' with home_stats='active' %}

    
    <!-- Page Content Start -->
    <div class="container">
      <h1 class="welcome">WELCOME!</h1>
    </div>
    <div clas="box">
        <div class="contentA">
                <h1 class="apaitu">APA ITU</h1>
                <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
                <p class="desc-apa">
                    Trash-IT adalah aplikasi yang akan membantu anda <br>
                    dalam pembuangan sampah. Trash-It memberikan layanan <br>
                    penjemputan sampah dengan bayaran sesuai dengan jenis <br>
                    sampah dan berat sampah yang anda berikan ke kami. <br>
                </p>
                <img class="logo-a" src="/static/img/Logo 3.png" alt="">
        </div>
        <div class="contentB">
            <h1 class="mengapa">MENGAPA</h1>
            <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
            <div class="container-desc">
                <p class="desc-mengapa">
                • Praktis & Mudah <br>
                • Efisiensi waktu <br>
                • Ramah Lingkungan <br>
                </p>
                <img class="logo-b" src="/static/img/Logo 2.png" alt="">
            </div>
        </div>
        <div class="tutorial text-center">
            <p class="desc-button">Pelajari Cara Memakai App Ini</p>
            <a href={% url 'tutorial' %}>
                <button type="button" class="btn btn-primary btn-lg">TUTORIAL</button>
            </a>
            <p class="desc-button">Siap Membersihkan Bumi?</p>
            <a href={% url 'buangsampah:buangsampah' %}>
                <button type="button" class="btn btn-primary btn-lg">SIAP!</button>
        
            </a>
        </div>
        <div>
            <h1 class="contact">CONTACT US</h1>
            <h3 class="info">
                example@trash-it.com <br>
                021-72991 <br> <br>
            </h3>
        </div>
    </div>
    <!-- Page Content End -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

home/templates/navbar.html
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img style="height: auto; width: 150px;" src="/static/img/Logo 1.png" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {{ home_stats }}">
            <a class="nav-link" href={% url 'home' %}>Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item  {{ buangsampah_stats }}">
            <a class="nav-link" href="{% url 'buangsampah:buangsampah' %}">Buang Sampah</a>
            </li>
            <li class="nav-item {{ faq_stats }}">
            <a class="nav-link" href={% url 'faq' %}>FAQ</a>
            </li>
            <li class="nav-item {{ tutorial_stats }}">
            <a class="nav-link" href={% url 'tutorial' %}>Tutorial</a>
            </li>
            <li class="nav-item {{ profile_stats }}">
                <a class="nav-link" href={% url 'accmgr:profile' %}>Profile</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

templates/home.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_home.css' %}">

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">

    <title>TRASH-IT</title>
</head>

<body>
    <!-- Navigation Bar -->
    {% include 'navbar.html' with home_stats='active' %}

    
    <!-- Page Content Start -->
    <div class="container">
      <h1 class="welcome">WELCOME!</h1>
    </div>
    <div clas="box">
        <div class="contentA">
                <h1 class="apaitu">APA ITU</h1>
                <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
                <p class="desc-apa">
                    Trash-IT adalah aplikasi yang akan membantu anda <br>
                    dalam pembuangan sampah. Trash-It memberikan layanan <br>
                    penjemputan sampah dengan bayaran sesuai dengan jenis <br>
                    sampah dan berat sampah yang anda berikan ke kami. <br>
                </p>
                <img class="logo-a" src="/static/img/Logo 3.png" alt="">
        </div>
        <div class="contentB">
            <h1 class="mengapa">MENGAPA</h1>
            <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
            <div class="container-desc">
                <p class="desc-mengapa">
                • Praktis & Mudah <br>
                • Efisiensi waktu <br>
                • Ramah Lingkungan <br>
                </p>
                <img class="logo-b" src="/static/img/Logo 2.png" alt="">
            </div>
        </div>
        <div class="tutorial text-center">
            <p class="desc-button">Pelajari Cara Memakai App Ini</p>
            <a href={% url 'tutorial' %}>
                <button type="button" class="btn btn-primary btn-lg">TUTORIAL</button>
            </a>
            <p class="desc-button">Siap Membersihkan Bumi?</p>
            <a href={% url 'buangsampah:buangsampah' %}>
                <button type="button" class="btn btn-primary btn-lg">SIAP!</button>
        
            </a>
        </div>
        <div>
            <h1 class="contact">CONTACT US</h1>
            <h3 class="info">
                example@trash-it.com <br>
                021-72991 <br> <br>
            </h3>
        </div>
    </div>
    <!-- Page Content End -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img style="height: auto; width: 150px;" src="/static/img/Logo 1.png" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {{ home_stats }}">
            <a class="nav-link" href={% url 'home' %}>Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item  {{ buangsampah_stats }}">
            <a class="nav-link" href="{% url 'buangsampah:buangsampah' %}">Buang Sampah</a>
            </li>
            <li class="nav-item {{ faq_stats }}">
            <a class="nav-link" href={% url 'faq' %}>FAQ</a>
            </li>
            <li class="nav-item {{ tutorial_stats }}">
            <a class="nav-link" href={% url 'tutorial' %}>Tutorial</a>
            </li>
            <li class="nav-item {{ profile_stats }}">
                <a class="nav-link" href={% url 'accmgr:profile' %}>Profile</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

templates/new_home.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with home_stats='active' %}
{% endblock %}
    
{% block includedcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_home.css' %}">
{% endblock %}
    
{% block content %}
<div class="container">
  <h1 class="welcome">WELCOME!</h1>
</div>
<div clas="box">
    <div class="contentA">
            <h1 class="apaitu">APA ITU</h1>
            <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
            <p class="desc-apa">
                Trash-IT adalah aplikasi yang akan membantu anda <br>
                dalam pembuangan sampah. Trash-It memberikan layanan <br>
                penjemputan sampah dengan bayaran sesuai dengan jenis <br>
                sampah dan berat sampah yang anda berikan ke kami. <br>
            </p>
            <img class="logo-a" src="{% static 'img/Logo 3.png' %}" alt="">
    </div>
    <div class="contentB">
        <h1 class="mengapa">MENGAPA</h1>
        <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
        <div class="container-desc">
            <p class="desc-mengapa">
            • Praktis & Mudah <br>
            • Efisiensi waktu <br>
            • Ramah Lingkungan <br>
            </p>
            <img class="logo-b" src="{% static 'img/Logo 2.png' %}" alt="">
        </div>
    </div>
    <div class="tutorial text-center">
        <p class="desc-button">Pelajari Cara Memakai App Ini</p>
        <a href="{% url 'tutorial' %}">
            <button type="button" class="btn btn-primary btn-lg">TUTORIAL</button>
        </a>
        <p class="desc-button">Siap Membersihkan Bumi?</p>
        <a href="{% url 'buangsampah:buangsampah' %}">
            <button type="button" class="btn btn-primary btn-lg">SIAP!</button>
    
        </a>
    </div>
    <div>
        <h1 class="contact">CONTACT US</h1>
        <h3 class="info">
            example@trash-it.com <br>
            021-72991 <br> <br>
        </h3>
    </div>
</div>
{% endblock %}
    

templates/new_navbar.html
{% load static %}
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img style="height: auto; width: 150px;" src="{% static 'img/Logo 1.png' %}" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {{ home_stats }}">
            <a class="nav-link" href={% url 'home' %}>Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item  {{ buangsampah_stats }}">
            <a class="nav-link" href="{% url 'buangsampah:buangsampah' %}">Buang Sampah</a>
            </li>
            <li class="nav-item {{ faq_stats }}">
            <a class="nav-link" href={% url 'faq' %}>FAQ</a>
            </li>
            <li class="nav-item {{ tutorial_stats }}">
            <a class="nav-link" href={% url 'tutorial' %}>Tutorial</a>
            </li>
            <li class="nav-item {{ profile_stats }}">
                <a class="nav-link" href={% url 'accmgr:profile' %}>Profile</a>
            </li>
        </ul>
        </div>
    </div>
</nav>